// Country dataset with flag emoji + REST Countries API flag URL
const COUNTRIES = [
    { name:"Afghanistan", capital:"Kabul", region:"Asia", subregion:"Southern Asia", population:40218234, language:"Dari", currency:"Afghan afghani (AFN)", flag:"🇦🇫", code:"AF" },
    { name:"Argentina", capital:"Buenos Aires", region:"Americas", subregion:"South America", population:45376763, language:"Spanish", currency:"Argentine peso (ARS)", flag:"🇦🇷", code:"AR" },
    { name:"Australia", capital:"Canberra", region:"Oceania", subregion:"Australia and New Zealand", population:25687041, language:"English", currency:"Australian dollar (AUD)", flag:"🇦🇺", code:"AU" },
    { name:"Brazil", capital:"Brasília", region:"Americas", subregion:"South America", population:214326223, language:"Portuguese", currency:"Brazilian real (BRL)", flag:"🇧🇷", code:"BR" },
    { name:"Canada", capital:"Ottawa", region:"Americas", subregion:"North America", population:38005238, language:"English", currency:"Canadian dollar (CAD)", flag:"🇨🇦", code:"CA" },
    { name:"China", capital:"Beijing", region:"Asia", subregion:"Eastern Asia", population:1402112000, language:"Chinese", currency:"Chinese yuan (CNY)", flag:"🇨🇳", code:"CN" },
    { name:"Egypt", capital:"Cairo", region:"Africa", subregion:"Northern Africa", population:102334404, language:"Arabic", currency:"Egyptian pound (EGP)", flag:"🇪🇬", code:"EG" },
    { name:"France", capital:"Paris", region:"Europe", subregion:"Western Europe", population:67391582, language:"French", currency:"Euro (EUR)", flag:"🇫🇷", code:"FR" },
    { name:"Germany", capital:"Berlin", region:"Europe", subregion:"Central Europe", population:83240525, language:"German", currency:"Euro (EUR)", flag:"🇩🇪", code:"DE" },
    { name:"India", capital:"New Delhi", region:"Asia", subregion:"Southern Asia", population:1380004385, language:"Hindi", currency:"Indian rupee (INR)", flag:"🇮🇳", code:"IN" },
    { name:"Indonesia", capital:"Jakarta", region:"Asia", subregion:"South-Eastern Asia", population:273523621, language:"Indonesian", currency:"Indonesian rupiah (IDR)", flag:"🇮🇩", code:"ID" },
    { name:"Italy", capital:"Rome", region:"Europe", subregion:"Southern Europe", population:59554023, language:"Italian", currency:"Euro (EUR)", flag:"🇮🇹", code:"IT" },
    { name:"Japan", capital:"Tokyo", region:"Asia", subregion:"Eastern Asia", population:125836021, language:"Japanese", currency:"Japanese yen (JPY)", flag:"🇯🇵", code:"JP" },
    { name:"Kenya", capital:"Nairobi", region:"Africa", subregion:"Eastern Africa", population:53771296, language:"Swahili", currency:"Kenyan shilling (KES)", flag:"🇰🇪", code:"KE" },
    { name:"Mexico", capital:"Mexico City", region:"Americas", subregion:"North America", population:128932753, language:"Spanish", currency:"Mexican peso (MXN)", flag:"🇲🇽", code:"MX" },
    { name:"Netherlands", capital:"Amsterdam", region:"Europe", subregion:"Western Europe", population:17441139, language:"Dutch", currency:"Euro (EUR)", flag:"🇳🇱", code:"NL" },
    { name:"New Zealand", capital:"Wellington", region:"Oceania", subregion:"Australia and New Zealand", population:5084300, language:"English", currency:"New Zealand dollar (NZD)", flag:"🇳🇿", code:"NZ" },
    { name:"Nigeria", capital:"Abuja", region:"Africa", subregion:"Western Africa", population:206139587, language:"English", currency:"Nigerian naira (NGN)", flag:"🇳🇬", code:"NG" },
    { name:"Pakistan", capital:"Islamabad", region:"Asia", subregion:"Southern Asia", population:220892331, language:"Urdu", currency:"Pakistani rupee (PKR)", flag:"🇵🇰", code:"PK" },
    { name:"Russia", capital:"Moscow", region:"Europe", subregion:"Eastern Europe", population:144104080, language:"Russian", currency:"Russian ruble (RUB)", flag:"🇷🇺", code:"RU" },
    { name:"Saudi Arabia", capital:"Riyadh", region:"Asia", subregion:"Western Asia", population:34813867, language:"Arabic", currency:"Saudi riyal (SAR)", flag:"🇸🇦", code:"SA" },
    { name:"South Africa", capital:"Pretoria", region:"Africa", subregion:"Southern Africa", population:59308690, language:"Zulu", currency:"South African rand (ZAR)", flag:"🇿🇦", code:"ZA" },
    { name:"South Korea", capital:"Seoul", region:"Asia", subregion:"Eastern Asia", population:51780579, language:"Korean", currency:"South Korean won (KRW)", flag:"🇰🇷", code:"KR" },
    { name:"Spain", capital:"Madrid", region:"Europe", subregion:"Southern Europe", population:47351567, language:"Spanish", currency:"Euro (EUR)", flag:"🇪🇸", code:"ES" },
    { name:"Thailand", capital:"Bangkok", region:"Asia", subregion:"South-Eastern Asia", population:69799978, language:"Thai", currency:"Thai baht (THB)", flag:"🇹🇭", code:"TH" },
    { name:"Turkey", capital:"Ankara", region:"Asia", subregion:"Western Asia", population:84339067, language:"Turkish", currency:"Turkish lira (TRY)", flag:"🇹🇷", code:"TR" },
    { name:"Ukraine", capital:"Kyiv", region:"Europe", subregion:"Eastern Europe", population:44134693, language:"Ukrainian", currency:"Ukrainian hryvnia (UAH)", flag:"🇺🇦", code:"UA" },
    { name:"United Kingdom", capital:"London", region:"Europe", subregion:"Northern Europe", population:67886011, language:"English", currency:"Pound sterling (GBP)", flag:"🇬🇧", code:"GB" },
    { name:"United States", capital:"Washington D.C.", region:"Americas", subregion:"North America", population:329484123, language:"English", currency:"United States dollar (USD)", flag:"🇺🇸", code:"US" },
    { name:"Vietnam", capital:"Hanoi", region:"Asia", subregion:"South-Eastern Asia", population:97338583, language:"Vietnamese", currency:"Vietnamese đồng (VND)", flag:"🇻🇳", code:"VN" }
];
